services:
  http-app-server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - http-app-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  http-app-database:
    container_name: http-app-database
    image: mysql:8
    restart: always
    networks:
      - http-app-network
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env

networks:
  http-app-network:
    driver: bridge

volumes:
  database-data:
    driver: local